fio_cruz_saude:
    resource: "@FioCruzSaudeBundle/Controller/"
    type:     annotation
    prefix:   /

fio_cruz_tarefas:
    resource: "@FioCruzTarefasBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
