<?php

namespace FioCruz\TarefasBundle\Repository;

/**
 * TarefaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarefaRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Retorna as tarefas cadastradas
     * @return array
     */
    public function getTarefas($dataCriacao = '2015-11-25')
    {
        $queryBuilder = $this->createQueryBuilder('t')
            ->addSelect('s')
            ->join('t.status', 's')
            ->where("t.dtCriacao > :dataDeCriacao")
            ->orderBy("t.coTarefa")
            ->setParameter('dataDeCriacao', $dataCriacao);

        return $queryBuilder->getQuery()->getResult();
    }

    public function deletar($tarefa)
    {
        $qb = $this->createQueryBuilder('t');
        $qb->delete()
            ->where('t.coTarefa = :tarefa')
            ->setParameter('tarefa', $tarefa);

        $qb->getQuery()->execute();
    }
}
