<?php

namespace FioCruz\TarefasBundle\Repository;

/**
 * TarefaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarefaRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Retorna as tarefas cadastradas
     * @return array
     */
    public function getTarefas($dataCriacao = '2015-11-25')
    {
        $queryBuilder = $this->createQueryBuilder('t')
            ->where("t.dtCriacao > :dataDeCriacao")
            ->orderBy("t.dsTitulo")
            ->setParameter('dataDeCriacao', $dataCriacao);
        
        return $queryBuilder->getQuery()->getResult();
    }
}
